### PR TITLE
New logo for Downloader

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by reallinfo** [comment]
I wanted to contribute to Downloader. I designed a logo for it. I hope you like it :) 
If you have something you want, do not hesitate to write it down.

Here all the editable files.

https://drive.google.com/open?id=14m7mccIMfw233Y0N7puc9esOSmO0F0R6

**Comment by Johann-S** [comment]
Maybe you can add your favicon to the main page ? 
https://github.com/Strikesoft/Downloader/blob/master/views/base/base.twig

**Comment by reallinfo** [comment]
Sorry, I'm not sure where to add Favicon. I can design a favicon size and format you want. Could you add that?

**Comment by Johann-S** [comment]
Just a quick change, can you move your files in `web/img/logo` please ?

**Comment by reallinfo** [comment]
Sure, I sent a new pr.

https://github.com/Strikesoft/Downloader/pull/42

Btw, Also i added favicon version.

**Comment by Johann-S** [comment]
Thanks 👍 I close this one and merge the other one :wink:

**Pull request closed without merging**
